"""
Report Utilities
================
Builds the structured report dict and persists it to disk.
"""

import json
import os
from datetime import datetime
from pathlib import Path

from detector.scoring import (
    compute_confidence,
    compute_verdict,
    build_explanation,
    build_suspicious_signals,
)


DISCLAIMER = (
    "This report is generated by DeepFake Shield using statistical heuristics and "
    "placeholder detection logic. It is NOT forensic evidence and should NOT be used "
    "for legal, medical, journalistic, or law-enforcement purposes. Results may contain "
    "false positives and false negatives. Always consult qualified experts for critical decisions."
)


def generate_report(filename: str, file_type: str, result: dict) -> dict:
    """
    Build a structured report dictionary from an analysis result.

    Parameters
    ----------
    filename  : str   Original filename
    file_type : str   "image" or "video"
    result    : dict  Output of analyze_image() or analyze_video()

    Returns
    -------
    dict  Full report (serialisable to JSON)
    """
    if result.get("error"):
        return {
            "status":          "error",
            "error_message":   result["error"],
            "filename":        filename,
            "media_type":      file_type,
            "generated_at":    _now(),
            "disclaimer":      DISCLAIMER,
        }

    ai_prob  = result["ai_probability"]
    signals  = result.get("signals", {})
    face     = result.get("face_detected", False)

    verdict    = compute_verdict(ai_prob)
    confidence = compute_confidence(signals)
    explanation = build_explanation(verdict, signals, face)
    suspicious  = build_suspicious_signals(signals)

    report = {
        "status":            "success",
        "generated_at":      _now(),
        "filename":          filename,
        "media_type":        file_type,
        # ── Core metrics ─────────────────────────────────────────────────
        "verdict":           verdict,
        "ai_probability":    round(ai_prob, 4),
        "confidence_level":  confidence,
        # ── Narrative ────────────────────────────────────────────────────
        "explanation":       explanation,
        "suspicious_signals": suspicious,
        # ── Detailed breakdown ────────────────────────────────────────────
        "signal_breakdown":  {k: round(v, 4) for k, v in signals.items()},
        "technical_details": result.get("technical_details", {}),
        # ── Video extras ──────────────────────────────────────────────────
        "suspicious_frames": result.get("suspicious_frames", []),
        "frame_scores":      [round(s, 4) for s in result.get("frame_scores", [])],
        # ── Legal ─────────────────────────────────────────────────────────
        "disclaimer":        DISCLAIMER,
    }

    return report


def save_report(report: dict, directory: str = "reports") -> str:
    """
    Persist a report as a JSON file.

    Returns the path to the saved file.
    """
    Path(directory).mkdir(parents=True, exist_ok=True)

    ts    = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    name  = f"report_{ts}.json"
    path  = Path(directory) / name

    path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
